### ISSUE TITLE
Incorrect program name in tray on KDE

### ISSUE THREAD

**Issue by Den4enko** [mrmoein/warp-cloudflare-gui#8]
![Screenshot_20220509_224850](https://user-images.githubusercontent.com/60628208/167486673-a0e5d76c-63fd-4ceb-b866-79c1b9bd3f1a.png)
Hi! The name of this program does not show up correctly in the tray (main.py). I suggest that it should be: "Warp" or "1.1.1.1"

**Comment by mrmoein** [comment]
unfortunately i dont have kde, but i changed the process title, can you try the branch [8-incorrect-program-name-in-tray-on-kde ](https://github.com/mrmoein/warp-cloudflare-gui/tree/8-incorrect-program-name-in-tray-on-kde) and let me know about the result?

    $ git fetch origin
    $ git pull origin 8-incorrect-program-name-in-tray-on-kde
    $ git checkout 8-incorrect-program-name-in-tray-on-kde
    $ python install.py

**Comment by Den4enko** [comment]
Unfortunately, nothing changed
![Screenshot_20220514_111556](https://user-images.githubusercontent.com/60628208/168422655-4446163a-cbbd-4223-b20b-5b0f48a26b0e.png)

**Comment by mrmoein** [comment]
I tried my best and could not find anything related to this problem. There is no such thing in the ubuntu tray icons. maybe somebody else can fix it or at least guide me.

**Comment by parampreetss** [comment]
Hi @mrmoein,
I was able to fix it in KDE. In mainwindow.py, I made the following additions:

`class GUI:
    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.app.setApplicationName('Cloudflare Warp')`
This gives a name to the application instead of using main.py.

`    def set_tray_icon(self, connected):
        if connected:
            self.tray_icon.setIcon(QIcon(os.path.dirname(__file__) + '/../icons/online.png'))
            self.tray_icon.setToolTip('Connected')
        else:
            self.tray_icon.setIcon(QIcon(os.path.dirname(__file__) + '/../icons/offline.png'))
            self.tray_icon.setToolTip('Disconnected')`
This sets a tool tip with the current status. I wanted to remove the hard coded "Connected" and "Disconnected" using the variable 'status' from the function status_thread. But the call to the function set_tray_icon from here doesn't pass the status variable, so I used hard coded values for the time being.

Also, this check `if self.last_status != status:` in status_thread doesn't let it set the tool tip value at the launch of the GUI. Only after a status change does it set the tool tip.

Hope this is of some use to you.

**Comment by Den4enko** [comment]
Could you create a fork and upload it to github? I want to test it. And if all goes well, just create a pull request

**Comment by parampreetss** [comment]
I haven't ever done that (creating a fork and pull requests). So I'd need some time to learn the process, before I upload the change.

**Comment by parampreetss** [comment]
@Den4enko uploaded in a fork. Please check parampreetss/warp-cloudflare-gui

**Comment by parampreetss** [comment]
@mrmoein @Den4enko - has anyone tested the update?

**Comment by mrmoein** [comment]
Fixed https://github.com/mrmoein/warp-cloudflare-gui/commit/4f1a13798687df9ddfa3addc089ef6bce86ef5bb
